name: dengueQA

channels:
- bioconda
- conda-forge
- defaults

dependencies:
- cvxopt
- fasttree
- iqtree
- raxml
- mafft
- augur
- python=3.7*
- pandas
- biopython
- blast
- artemis
- unidecode
- snakemake-minimal
- pip

- pip:
  - numpy
  - matplotlib
  - epiweeks
  - pycountry-convert
  - pycountry